#! /bin/sh

# Start a development application server at 127.0.0.1:8000
#
# If no SQLite database exists, this tool sets up the application file system links and database schemes.
# You must execute this tool at the ROOT DIRECTORY of the site.


mkdir -p ./var/log
if [ ! -e "./settings_development.py" ]; then
   echo "Creating link to settings_development.py"
   ln -s ./support/configs/settings_development.py ./settings.py
fi

if [ ! -f "./var/db.sqlite" ]; then
   ./tools/setup settings &&
   ./tools/setup_fixtures settings
fi

./manage.py runserver
