#! /usr/bin/env python

import sys, re, base64, os.path

URL_MATCHER = re.compile(r'''url\(\s*['"]?(\S+)['"]?\s*\)''')
MIME_TYPES = {".png": "image/png",
              ".jpg": "image/jpeg",
              ".gif": "image/gif"}


css_file = sys.argv[1]
dir_name = os.path.dirname(css_file)


def inject(match):
   resource = os.path.join(dir_name, match.group(1))
   extension = resource.lower()[resource.rfind(".") :]
   mime_type = MIME_TYPES.get(extension, None)
   if mime_type is None or not os.path.exists(resource):
      return match.group(0)
   print >> sys.stderr, "Injecting", resource
   return '''url(data:%s;base64,
   %s
   )''' % (mime_type, base64.standard_b64encode(open(resource).read()))

print URL_MATCHER.sub(inject, open(css_file).read())
