#! /bin/sh

# Installs basic data for a clean app.
# Execute this tool at the ROOT DIRECTORY of the site.

. ./tools/require_settings.include.sh

load() {
   local dir=./support/fixtures
   local number=$1
   local name=$2
   local file="${dir}/${number}_${name}.json"
   echo ""
   echo "[i] ${number}: ${name}"
   if [ -e $file ] ; then 
      ./manage.py loaddata --settings "${SETTINGS}" $file
   else
      echo "[!] CANNOT FIND FIXTURE: ${file}"
      exit 1
   fi  
}

echo "[i] installing BASE fixtures (1-3)"

load 1 django_base
load 2 photologue_base
load 3 blogging_base

if [[ "${SETTINGS}" == "settings_development" ]] ; then
   echo "[i] installing DEVELOPMENT fixtures (4-6)"
   load 4 photologue_galleries
   load 5 blogging_articles
   load 6 django_history
   echo "[i] installing DEVELOPMENT photologue images"
   tar -xjf ./support/fixtures/photos.tar.bz2 -C ./var/public/galleries/
fi

echo "[i] done."

