#! /bin/sh

# Execute this tool at the root of the site.

# Sets up the application file system links and database schemas.
# DELETES all contents of the database!


# You may want to delete the actual database files first.
# SQLite:
#   > rm -f ../var/db.sqlite
# PostgreSQL (as postgres):
#   > dropdb thefoundation; createdb -O thefoundation thefoundation
#   > ./manage.py dbshell --settings "${SETTINGS}"

mkdir -p ../var
mkdir -p ../var/backup
mkdir -p ../log
mkdir -p ../run

echo "[i] Linking ./var/public/photos into the ./media"
mkdir -p ../var/public/galleries/photos
mkdir -p ../var/public/galleries/temp
# recreate current link if missing
( cd ./media ; ln -s ../../var/public/galleries )

echo "[i] syncing db..."
./manage.py syncdb --noinput
echo "[i] flushing db..."
./manage.py sqlflush --settings "${SETTINGS}" | ./manage.py dbshell
